version: '3'

services:

  mysql:
    container_name: cormorant_db
    image: mysql:8
    environment:
      MYSQL_DATABASE: $WORDPRESS_DB_NAME
      MYSQL_USER: $WORDPRESS_DB_USER
      MYSQL_PASSWORD: $WORDPRESS_DB_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    # MYSQL 8 needs this for proper auth the `wordpress_cli`.
    command: --default-authentication-plugin=mysql_native_password

  wordpress:
    container_name: cormorant_wp
    image: wordpress:$WP_VERSION-apache
    depends_on:
      - mysql
    ports:
      - 127.0.0.1:8000:80
    env_file:
      - .env
    volumes:
      - wp_data:$WP_CORE_DIR
      - ./cormorant:/var/www/html/wp-content/plugins/cormorant:ro
  
  # WP CLI for Wordpress configuration
  # Runs the `wp-config.sh` on startup.
  wp-cli:
    container_name: cormorant_wp_cli
    image: wordpress:cli
    depends_on:
      - mysql
      - wordpress
    user: xfs
    env_file:
      - .env
    volumes:
      - wp_data:$WP_CORE_DIR
      - ./utils/wp-cli:/opt/utils:ro
    command: /opt/utils/wp-config.sh

  # PHP Composer, PHPUnit, WP testlib, Cormorant tests
  test:
    container_name: cormorant_test
    image: composer:latest
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - ./tmp/composer:/app
      - ./tmp/testlib:$WP_TESTS_DIR
      - wp_data:$WP_CORE_DIR
      - ./tests:/var/lib/wordpress/cormorant-tests:ro
      - ./utils/test:/opt/utils:ro
    command: bash
    tty: true

volumes:
  db_data:
  wp_data:
