version: '3'

services:

  mysql:
    container_name: cormorant_db
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
    # MYSQL 8 needs this for proper auth the `wordpress_cli`.
    command: --default-authentication-plugin=mysql_native_password

  wordpress:
    container_name: cormorant_wp
    build:
      context: .
      args:
        WORDPRESS_VERSION: ${WORDPRESS_VERSION}
    depends_on:
      - mysql
    ports:
      - 127.0.0.1:8000:80
    env_file:
      - ./.env
    volumes:
      - wp_data:/var/www/html
      - ./cormorant:/var/www/html/wp-content/plugins/cormorant

  # Entry point to Wordpress configuration.
  wordpress_cli:
    container_name: cormorant_wp_cli
    image: wordpress:cli
    depends_on:
      - mysql
      - wordpress
    user: xfs
    env_file:
      - ./.env
    volumes:
      - wp_data:/var/www/html/
      - ./wp-config.sh:/opt/wp-config.sh
    command: bash /opt/wp-config.sh

volumes:
  wp_data:
  db_data:
